export enum ErrorCode {
  // Validation Errors (400)
  VAL_INVALID_INPUT = 'VAL_INVALID_INPUT',
  VAL_MISSING_FIELD = 'VAL_MISSING_FIELD',
  VAL_INVALID_EMAIL = 'VAL_INVALID_EMAIL',
  VAL_INVALID_PASSWORD = 'VAL_INVALID_PASSWORD',
  VAL_LAPTOP_NOT_AVAILABLE = 'VAL_LAPTOP_NOT_AVAILABLE',
  VAL_LAPTOP_NOT_CHECKED_OUT = 'VAL_LAPTOP_NOT_CHECKED_OUT',
  VAL_UNAUTHORIZED_CHECKIN = 'VAL_UNAUTHORIZED_CHECKIN',
  VAL_UNAUTHORIZED_ACTION = 'VAL_UNAUTHORIZED_ACTION',

  // Authentication Errors (401)
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_NO_TOKEN = 'AUTH_NO_TOKEN',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',

  // Authorization Errors (403)
  PERM_ADMIN_REQUIRED = 'PERM_ADMIN_REQUIRED',
  PERM_ACCESS_DENIED = 'PERM_ACCESS_DENIED',

  // Resource Not Found (404)
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  NOT_FOUND_LAPTOP = 'NOT_FOUND_LAPTOP',
  NOT_FOUND_CHECKOUT = 'NOT_FOUND_CHECKOUT',

  // Business Logic Errors (409)
  BIZ_LAPTOP_NOT_AVAILABLE = 'BIZ_LAPTOP_NOT_AVAILABLE',
  BIZ_USER_HAS_ACTIVE_CHECKOUT = 'BIZ_USER_HAS_ACTIVE_CHECKOUT',
  BIZ_LAPTOP_ALREADY_CHECKED_OUT = 'BIZ_LAPTOP_ALREADY_CHECKED_OUT',
  BIZ_EMAIL_ALREADY_EXISTS = 'BIZ_EMAIL_ALREADY_EXISTS',
  BIZ_NO_ACTIVE_CHECKOUT = 'BIZ_NO_ACTIVE_CHECKOUT',
  BIZ_INVALID_CHECKIN = 'BIZ_INVALID_CHECKIN',

  // Rate Limiting (429)
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Server Errors (500)
  SRV_DATABASE_ERROR = 'SRV_DATABASE_ERROR',
  SRV_EMAIL_SEND_FAILED = 'SRV_EMAIL_SEND_FAILED',
  SRV_INTERNAL_ERROR = 'SRV_INTERNAL_ERROR',
  SRV_QR_GENERATION_FAILED = 'SRV_QR_GENERATION_FAILED',
}
